name: check-pr

on: [pull_request]

jobs:
  check-pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - name: install dependencies
        run: yarn --production=false
      - name: lint
        run: yarn lint
      - name: tsc
        run: yarn tsc
